Repository TeamWisp/WispRenderer, pull requests merged in 2019-05, with the labels that each got.

#274 Save Render targets to disc.
  src/d3d12/d3d12_functions.hpp
  src/d3d12/d3d12_render_target.cpp
  src/d3d12/d3d12_render_window.cpp
  src/d3d12/d3d12_renderer.cpp
  src/d3d12/d3d12_renderer.hpp
  src/d3d12/d3d12_structs.hpp
  src/frame_graph/frame_graph.cpp
  src/frame_graph/frame_graph.hpp
  src/render_tasks/d3d12_save_image.hpp
  src/renderer.cpp
  src/renderer.hpp
Labels: enhancement

#283 Refactored render tasks to better use the descriptor heap.
  src/render_tasks/d3d12_deferred_composition.cpp
  src/render_tasks/d3d12_deferred_composition.hpp
  src/render_tasks/d3d12_path_tracer.hpp
  src/render_tasks/d3d12_rt_hybrid_task.hpp
Labels: code change

#267 Feature refactor materials
  demo/scene_emibl.hpp
  demo/scene_spheres.hpp
  demo/scene_viknell.hpp
  resources/shaders/material_util.hlsl
  src/d3d12/d3d12_renderer.cpp
  src/d3d12/d3d12_resource_pool_texture.cpp
  src/d3d12/d3d12_resource_pool_texture.hpp
  src/material_pool.cpp
  src/material_pool.hpp
  src/model_loader.hpp
  src/model_pool.hpp
  src/render_tasks/d3d12_build_acceleration_structures.hpp
  src/render_tasks/d3d12_path_tracer.hpp
  src/render_tasks/d3d12_raytracing_task.hpp
  src/render_tasks/d3d12_rt_hybrid_task.hpp
  src/resource_pool_texture.cpp
  src/resource_pool_texture.hpp
  src/structs.hpp
Labels: code change

#194 Feature rtao
  imgui.ini
  resources/shaders/ambient_occlusion.hlsl
  resources/shaders/deferred_composition.hlsl
  resources/shaders/lighting.hlsl
  resources/shaders/rt_global.hlsl
  resources/shaders/rt_hybrid.hlsl
  resources/shaders/util.hlsl
  src/d3d12/d3d12_defines.hpp
  src/d3d12/d3d12_renderer.cpp
  src/d3d12/d3d12_renderer.hpp
  src/engine_registry.cpp
  src/engine_registry.hpp
  src/imgui_tools.cpp
  src/render_tasks/d3d12_deferred_composition.cpp
  src/render_tasks/d3d12_deferred_composition.hpp
  src/render_tasks/d3d12_raytracing_task.hpp
  src/render_tasks/d3d12_rt_hybrid_task.hpp
  src/render_tasks/d3d12_rtao_task.hpp
  tests/demo/demo_frame_graphs.hpp
Labels: enhancement

#305 Replaced sentry with bugsplat
  tests/demo/demo.cpp
Labels: enhancement

#308 Fixed Maya crashes
  src/window.cpp
Labels: bug

#310 Feature RTAO settings
  imgui.ini
  resources/shaders/ambient_occlusion.hlsl
  src/render_tasks/d3d12_rtao_task.hpp
  tests/demo/engine_interface.hpp
Labels: enhancement

#316 Feature successful maya compilation
  src/d3d12/d3d12_renderer.cpp
  src/frame_graph/frame_graph.hpp
Labels: bug, refactor

#241 Feature refactor skybox
  resources/shaders/path_tracer.hlsl
  resources/shaders/raytracing.hlsl
  resources/shaders/rt_hybrid.hlsl
  src/render_tasks/d3d12_equirect_to_cubemap.hpp
  src/render_tasks/d3d12_path_tracer.hpp
  src/render_tasks/d3d12_raytracing_task.hpp
  src/render_tasks/d3d12_rt_hybrid_task.hpp
  src/scene_graph/scene_graph.hpp
  tests/demo/scene_emibl.hpp
  tests/demo/scene_spheres.hpp
  tests/demo/scene_viknell.hpp
Labels: refactor
